apiVersion: v1
kind: Service
metadata:
  name: agentguard-server
  namespace: poc-agentguard
  labels:
    app: agentguard-server
    autopoc.io/project: agentguard
spec:
  type: ClusterIP
  selector:
    app: agentguard-server
  ports:
    - port: 38080
      targetPort: 38080
